### ISSUE TITLE
High Severity Vulnerability - Minimist -

### ISSUE THREAD

**Issue by IngridGdesigns** [indeedeng/Mariner#116]
there is no patch for it at the moment, closely watching this thread for updates: https://github.com/substack/minimist/issues/164 and this thread: https://security.snyk.io/vuln/SNYK-JS-MINIMIST-559764

**Comment by kevindigo** [comment]
Minimist is only a dev dependency, so the distributed library would not be vulnerable at all. 

From what I can tell, even for Mariner developers, the risk is low. Some code in one of our other dependencies would have to attempt the attack. 

I assume this will be fixed with jest and ts-jest come out with updates that use newer versions of minimist.

**Comment by IngridGdesigns** [comment]
closing issue, low risk
